#!/usr/bin/env php
<?php

declare(strict_types=1);

// Autoload.
$possibleFiles = [__DIR__.'/../../autoload.php', __DIR__.'/../autoload.php', __DIR__.'/vendor/autoload.php'];
$file = null;
foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;

        break;
    }
}

if (null === $file) {
    throw new RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

// Init and run fword.
(new \OmegaCode\FWord\Application())->run(dirname(realpath($argv[0])) . '/', $argv);
